import type { Metadata } from "next"
import { Exo_2 } from "next/font/google"
import PrimaryNavBar from "@/components/primary-navbar"
import "../globals.css"


const exo_2 = Exo_2({
  subsets: ['latin'],
  weight: "300",
  
});

export const metadata: Metadata = {
  title: "PowerPulse Fitness",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased overscroll-none overflow-x-hidden min-h-screen bg-gradient-to-tr from-black via-gray-800 to-black text-white ${exo_2.className}`}
      >
        <div className="flex flex-col space-y-5">
          <div className="pt-3 md:pl-10">
            <PrimaryNavBar />
          </div>
          <div className="md:pl-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
