import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "PowerPulse Fitness",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-gradient-to-tr from-black via-gray-800 to-black`}
      >
        {children}
      </body>
    </html>
  );
}
