import type { Metadata } from "next"
import { Exo_2 } from "next/font/google"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { UserDashboard } from "@/components/dash-sidebar"
import "../globals.css"

const exo_2 = Exo_2({
  subsets: ['latin'],
  weight: "300",
  
});


export const metadata: Metadata = {
  title: "PowerPulse Fitness",
  description: "Generated by create next app",
};

export default function MainFunctionalityLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased overscroll-none overflow-x-hidden min-h-screen bg-gradient-to-tr from-black via-gray-800 to-black text-white ${exo_2.className}`}
      >
        <SidebarProvider>
          <UserDashboard />
          <main>
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
