import type { Metadata } from "next"
import { Exo_2 } from "next/font/google"
import ReactQueryProvider from "@/lib/query"
import { TooltipProvider } from "@/components/ui/tooltip"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { UserDashboard } from "@/components/nav/dash-sidebar"
import { Toaster } from "@/components/ui/sonner"
import "../globals.css"

const exo_2 = Exo_2({
  subsets: ['latin'],
  weight: "300",
  
})


export const metadata: Metadata = {
  title: "PowerPulse Fitness",
  description: "Generated by create next app",
}

export default function MainFunctionalityLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased overscroll-none overflow-x-hidden min-h-screen bg-gradient-to-tr from-black via-gray-800 to-black text-white ${exo_2.className}`}
      >
        <ReactQueryProvider>
          <TooltipProvider>
            <SidebarProvider>
              <UserDashboard />
              <main>
                <SidebarTrigger />
                {children}
              </main>
              <Toaster />
            </SidebarProvider>
          </TooltipProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
